name: Update Naukri Resume

on:
  schedule:
    - cron: "40 2 * * *"   # 08:10 AM IST
    - cron: "30 10 * * *"  # 04:00 PM IST
  workflow_dispatch:

jobs:
  update-resume:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Naukri Bot
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python naukri_bot.py
